version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"  # Expose le port 8085 pour accéder à l'application
    volumes:
      - applogs:/app/logs

volumes:
  pgdata:
  applogs:
